# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdv < Formula
  desc "Terminal markdown viewer with GitHub-style rendering"
  homepage "https://github.com/AlexTSPower/mdv"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.1.0/mdv_0.1.0_darwin_amd64.tar.gz"
      sha256 "7296a0c7d84723eea3a1fdfb811ca2e7b5c2d250daed445230b0c9d8c42f15a7"

      define_method(:install) do
        bin.install "mdv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.1.0/mdv_0.1.0_darwin_arm64.tar.gz"
      sha256 "66688d55145a10eb0ac9040e130faa0decf73701c444fec0753132a0c20e6ce3"

      define_method(:install) do
        bin.install "mdv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.1.0/mdv_0.1.0_linux_amd64.tar.gz"
      sha256 "b0d761ee041f2bfb31435cd6adcaf34fe45c3ab0554794b66018622bcf4cc41b"
      define_method(:install) do
        bin.install "mdv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.1.0/mdv_0.1.0_linux_arm64.tar.gz"
      sha256 "b68e948da6118939e686f46b8ca0714155a95b6031e0aec35b8a1ec3a90a7447"
      define_method(:install) do
        bin.install "mdv"
      end
    end
  end

  test do
    system "#{bin}/mdv", "--version"
  end
end
