# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdv < Formula
  desc "Terminal markdown viewer with GitHub-style rendering"
  homepage "https://github.com/AlexTSPower/mdv"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.3.1/mdv_0.3.1_darwin_amd64.tar.gz"
      sha256 "1a91d489e044e150257cc5f910d4a15cc27c82fa177f9870515ebe7be178c317"

      define_method(:install) do
        bin.install "mdv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.3.1/mdv_0.3.1_darwin_arm64.tar.gz"
      sha256 "c6338dc4804541a6ff6d84b43a463078bdb650287e7aa174c983d2185b450efc"

      define_method(:install) do
        bin.install "mdv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.3.1/mdv_0.3.1_linux_amd64.tar.gz"
      sha256 "7e848d15f03ded33ae325179611dab8261476ab06111d14ac3f964d1daeb913a"
      define_method(:install) do
        bin.install "mdv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexTSPower/mdv/releases/download/v0.3.1/mdv_0.3.1_linux_arm64.tar.gz"
      sha256 "d41139f057b4a34d33e5ecc1f7f667442717de2c7502cf23e5d65bc9da6b9b1f"
      define_method(:install) do
        bin.install "mdv"
      end
    end
  end

  test do
    system "#{bin}/mdv", "--version"
  end
end
