# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stackreader < Formula
  desc "Terminal markdown viewer with GitHub-style rendering"
  homepage "https://github.com/AlexTSPower/StackReader"
  version "0.3.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AlexTSPower/StackReader/releases/download/v0.3.3/stackreader_0.3.3_darwin_amd64.tar.gz"
      sha256 "d77c1511a96e50e667b7ec4e3fe73e6343d3c0edd7d20604b9964b15878bed89"

      define_method(:install) do
        bin.install "stackreader"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AlexTSPower/StackReader/releases/download/v0.3.3/stackreader_0.3.3_darwin_arm64.tar.gz"
      sha256 "28af929f39d6ed2569ba24271a1a2e54fc52962cf5f8571ff23a106b06cdf5b4"

      define_method(:install) do
        bin.install "stackreader"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexTSPower/StackReader/releases/download/v0.3.3/stackreader_0.3.3_linux_amd64.tar.gz"
      sha256 "9e8d4e6121aab9906f90da43421678f67bb67de6462000ac4341dc28dd22b5ee"
      define_method(:install) do
        bin.install "stackreader"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AlexTSPower/StackReader/releases/download/v0.3.3/stackreader_0.3.3_linux_arm64.tar.gz"
      sha256 "835cbadbf7e82806e1b6ad3b4999208a101fbdb369063e35a979bb83b4bd04ef"
      define_method(:install) do
        bin.install "stackreader"
      end
    end
  end

  test do
    system "#{bin}/stackreader", "--version"
  end
end
